name: build

on:
  push:
    branches: [ "master" ]
    paths:
    - 'src/**'
    - 'injector/**'
    - 'launcher/**'
    - 'proxy/**'
    - 'unlocker/**'
    - '!**/README.md'
  pull_request:
    branches: [ "master" ]
    paths:
    - 'src/**'
    - 'injector/**'
    - 'launcher/**'
    - 'proxy/**'
    - 'unlocker/**'
    - '!**/README.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2.11.1
      id: changes
      with:
        filters: |
          tem:
            - 'src/**'
          injector:
            - 'injector/**'
          launcher:
            - 'launcher/**'
          proxy:
            - 'proxy/**'
          unlocker:
            - 'unlocker/**'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE }}
      shell: pwsh
      run: msbuild /m /p:Configuration=Release /p:Platform=x86 /t:${{ join(fromJson(steps.changes.outputs.changes), '`;') }}

    - name: Create artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        path: |
          bin/Release/**/*.dll
          bin/Release/**/*.exe
