name: build

on:
  push:
  pull_request:
    branches: [ "master" ]
    paths:
    - 'src/**'
    - 'injector/**'
    - 'launcher/**'
    - 'proxy/**'
    - 'unlocker/**'

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        project: [
          { target: tem, binary: tem.dll },
          { target: injector, binary: injector.exe },
          { target: launcher, binary: GridGameLauncher.exe },
          { target: proxy, binary: dinput8.dll },
          { target: unlocker, binary: unlocker.exe }
        ]

    runs-on: windows-latest

    if: contains(github.event.head_commit.message, '[ci build]')

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE }}
      run: msbuild /m /p:Configuration=Release /p:Platform=x86 /t:${{ matrix.project.target }}

    - name: Create artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v3
      with:
          name: ${{ matrix.project.target }}
          path: bin/Release/${{ matrix.project.target }}/${{ matrix.project.binary }}
