name: build

on:
  push:
    branches: [ "master" ]
    paths:
    - 'src/**'
    - 'injector/**'
    - 'launcher/**'
    - 'proxy/**'
    - 'unlocker/**'
  pull_request:
    branches: [ "master" ]
    paths:
    - 'src/**'
    - 'injector/**'
    - 'launcher/**'
    - 'proxy/**'
    - 'unlocker/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2.11.1
      id: changes
      with:
        filters: |
          tem:
            - 'src/**'
          injector:
            - 'injector/**'
          launcher:
            - 'launcher/**'
          proxy:
            - 'proxy/**'
          unlocker:
            - 'unlocker/**'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE }}
      shell: pwsh
      run: |
        $targets = @()

        if ('${{ steps.changes.outputs.tem }}' -eq 'true') { $targets += 'tem' }
        if ('${{ steps.changes.outputs.injector }}' -eq 'true') { $targets += 'injector' }
        if ('${{ steps.changes.outputs.launcher }}' -eq 'true') { $targets += 'launcher' }
        if ('${{ steps.changes.outputs.proxy }}' -eq 'true') { $targets += 'proxy' }
        if ('${{ steps.changes.outputs.unlocker }}' -eq 'true') { $targets += 'unlocker' }

        msbuild /m /p:Configuration=Release /p:Platform=x86 /t:$($targets -join  ';')

        if ('${{ steps.changes.outputs.tem }}' -eq 'true') {
          $Env:BUILD_WITH_XDEAD = '1'
          $Env:CL = '/D BUILD_WITH_XDEAD'

          msbuild /p:Configuration=Release /p:Platform=x86 /t:tem
        }

    - name: Create artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        path: |
          bin/Release/**/*.dll
          bin/Release/**/*.exe
