name: test

on:
  push:
    branches: [ "master" ]
    paths:
    - 'unlocker/**'
    paths-ignore:
    - '**/README.md'
  pull_request:
    branches: [ "master" ]
    paths:
    - 'unlocker/**'
    paths-ignore:
    - '**/README.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
        matrix:
          project: [
            { target: unlocker, binary: unlocker.exe }
          ]

    runs-on: windows-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v3
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE }}
      env:
        CL: /DBUILD_TESTS=1
      run: msbuild /m /p:Configuration=Release /p:Platform=x86 /t:${{ matrix.project.target }}

    - name: Run tests
      run: ./bin/Release/${{ matrix.project.target }}/${{ matrix.project.binary }}
